version: "3.2"

services:
  gql_postgres1:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
     - 1234:5432
    networks:
     - instance1


  gql_cassandra1:
    container_name: cassandra1
    build:
      context: .
      dockerfile: Dockerfile.cassandra
    volumes: 
      - ./docker-entrypoint.sh.cassandra:/docker-entrypoint.sh
      - ./cassandra-keyspace.cql:/docker-entrypoint-initdb.d/cassandra-keyspace.cql
    ports: 
      - 9042:9042
    environment: 
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    networks: 
      - instance1

  gql_science_db_graphql_server1:
    container_name: cassandra_test_box_gql_1
    depends_on:
      - gql_postgres1
    build:
      context: .
      dockerfile: Dockerfile.graphql_server
    volumes:
      - ./server1:/usr/src/app
      - ./data_models_storage_config1.json:/usr/src/app/config/data_models_storage_config.json
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      REQUIRE_SIGN_IN: "false"
      JQ_PATH: /usr/bin/jq
    # Await POSTGRES role and DB creation, migrate schema, then start web server:
    networks:
      - cassandra_test_box
      - instance1

    command:
      - /bin/sh
      - -c
      - |
        ./migrateDbAndStartServer.sh

  gql_postgres2:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
     - 1235:5431
    networks:
      - instance2

  gql_science_db_graphql_server2:
    container_name: cassandra_test_box_gql_2
    depends_on:
      - gql_postgres2
    build:
      context: .
      dockerfile: Dockerfile.graphql_server

    volumes:
      - ./server2:/usr/src/app
      - ./data_models_storage_config2.json:/usr/src/app/config/data_models_storage_config.json

    ports:
      - "3030:3030"

    environment:
      PORT: 3030
      REQUIRE_SIGN_IN: "false"
      JQ_PATH: /usr/bin/jq
    # Await POSTGRES role and DB creation, migrate schema, then start web server:
    networks:
      - cassandra_test_box
      - instance2
    command:
      - /bin/sh
      - -c
      - |
        ./migrateDbAndStartServer.sh

networks:
  instance1:
  instance2:
  cassandra_test_box:
