version: '3.8'

services:

  main_server:
    build:
      context: .
      dockerfile: Dockerfile.pgp
    volumes:
      - ./node_modules:/usr/src/app/node_modules
      - ./experiments/async-pg-promise:/usr/src/app
    networks:
      - backend

networks:
  backend: