version: "3.2"

services:
  sdb_postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - sdb_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  sdb_science_db_graphql_server:
    depends_on:
      - sdb_postgres
    build:
      context: ./graphql-server
      dockerfile: Dockerfile.graphql_server
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=production
    # Ensure there is enough room to upload large files and store them
    # temporarily in the host system's tempdir:
    volumes:
      - /tmp:/tmp
    # Await POSTGRES role and DB creation, migrate schema, then start web
    # server:
    command:
      - ./migrateDbAndStartServer.sh

  sdb_nginx:
    depends_on:
      - sdb_postgres
      - sdb_science_db_graphql_server
    build:
      context: ./single-page-app
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:80

volumes:
  sdb_db_data:
