version: "3.7"

services:
 sdb_science_db_app_server_local:
   build:
     context: ./spa_local/single-page-app
     dockerfile: Dockerfile.app
   ports:
     - 8080:8080
   environment:
     - PORT=8080
     - REACT_APP_CENZ_GRAPHQL_SERVER_URL=http://localhost:3000/graphql
     - REACT_APP_CENZ_LOGIN_URL=http://localhost:3000/login
     - REACT_APP_CENZ_EXPORT_URL=http://localhost:3000/export
     - REACT_APP_CENZ_MAX_UPLOAD_SIZE=500
   volumes:
     - ./spa_local:/usr/ScienceDbStarterPack
   networks:
     - CONABIO
   # Install dependencies and start single-page-app-server in development
   # mode.
   command:
     - /bin/sh
     - -c
     - |
       npm install
       npm start

networks:
  CONABIO:
    external: true
