version: "3.7"

services:
 sdb_science_db_app_server_internal:
   stdin_open: true # needed for react-scripts@3.4.1 https://github.com/facebook/create-react-app/issues/8688
   build:
     context: ./spa_internal/single-page-app
     dockerfile: Dockerfile.app
   ports:
     - 3002:3002
   environment:
     - PORT=3002
     - REACT_APP_ZENDRO_GRAPHQL_SERVER_URL=http://accesiones.conabio.gob.mx:3000/graphql
     - REACT_APP_ZENDRO_LOGIN_URL=http://accesiones.conabio.gob.mx:3000/login
     - REACT_APP_ZENDRO_EXPORT_URL=http://accesiones.conabio.gob.mx:3000/export
     - REACT_APP_ZENDRO_MAX_UPLOAD_SIZE=500
   volumes:
     - ./spa_internal:/usr/Sandbox
   networks:
     - CONABIO
   # Install dependencies and start single-page-app-server in development
   # mode.
   command:
     - /bin/sh
     - -c
     - |
       npm install
       npm start

networks:
  CONABIO:
    external: true
