version: "3.7"

services:
  sdb_postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - sdb_db_data:/var/lib/postgresql/data
    networks:
      - backend

  sdb_science_db_graphql_server:
    depends_on:
      - sdb_postgres
    build:
      context: ./graphql-server
      dockerfile: Dockerfile.graphql_server
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REQUIRE_SIGN_IN=false
    volumes:
      - .:/usr/Sandbox
      # Use the Sequelize config adjusted for the Docker setup of Sandbox:
      - ./graphql-server/config/config_postgres_docker.json:/usr/Sandbox/graphql-server/config/config.json
    networks:
      - backend
      - CONABIO
      - SIAGRO
    # Await POSTGRES role and DB creation, migrate schema, then start web
    # server:
    command:
      - /bin/sh
      - -c
      - |
        npm install
        ./migrateDbAndStartServer.sh

volumes:
  sdb_db_data:

networks:
  backend:
  SIAGRO:
    external: true
  CONABIO:
    external: true

