version: "3.7"

services:
  sdb_postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - sdb_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  sdb_science_db_graphql_server:
    depends_on:
      - sdb_postgres
    build:
      context: ./graphql-server
      dockerfile: Dockerfile.graphql_server
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    volumes:
      - .:/usr/Sandbox
      # Use the Sequelize config adjusted for the Docker setup of Sandbox:
      - ./graphql-server/config/config_postgres_docker.json:/usr/Sandbox/graphql-server/config/config.json
    # Await POSTGRES role and DB creation, migrate schema, then start web
    # server:
    command:
      - /bin/sh
      - -c
      - |
        npm install
        ./migrateDbAndStartServer.sh

  sdb_science_db_app_server:
    stdin_open: true # needed for react-scripts@3.4.1 https://github.com/facebook/create-react-app/issues/8688
    depends_on:
      - sdb_postgres
      - sdb_science_db_graphql_server
    build:
      context: ./single-page-app
      dockerfile: Dockerfile.app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - VUE_APP_SERVER_URL=http://localhost:3000/graphql
      - VUE_APP_LOGIN_URL=http://localhost:3000/login
      - VUE_APP_MAX_UPLOAD_SIZE=500
    volumes:
      - .:/usr/Sandbox
    # Install dependencies and start single-page-app-server in development
    # mode.
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run serve

  sdb_minio:
    image: minio/minio:RELEASE.2019-02-20T22-44-29Z
    volumes:
      - sdb_minio_data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: sciencedb
      MINIO_SECRET_KEY: sciencedb
    command: server /data

    #sdb_science_db_shiny:
    #bpbuild:
    #bp  context: .
    #bp  dockerfile: Dockerfile.shiny
    #bpenvironment:
    #bp  PORT: 3838
    #bpports:
    #bp  - "3838:3838"
    #bpvolumes:
    #bp  - ./shiny-data-dev:/srv/shiny-server
    #bp#labels:
    #bp#  traefik.enable: "true"
    #bp#  traefik.backend: "science_db_shiny"
    #bp#  traefik.frontend.rule: "Host:shiny.reconstructdb.org"
    #bp#  #traefik.frontend.auth.basic: 'testuser:$$apr1$$QBCuO60R$$pJIFSe2x8L/cTbOBOvoOt1'
    #bp#  traefik.docker.network: "reverseproxy"
    #bp#  traefik.port: "3838"

volumes:
  sdb_db_data:
  sdb_minio_data:
  #sdb_shiny_data:
