version: "3.8"

services:

  db_postgres:
    container_name: pgdb
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./initUserDb.sql:/docker-entrypoint-initdb.d/initUserDb.sql
    networks:
     - backend

  db_cassandra:
    container_name: cassandradb
    build:
      context: .
      dockerfile: Dockerfile.cassandra
    volumes: 
      - ./docker-entrypoint.sh.cassandra:/docker-entrypoint.sh
      - ./cassandra-keyspace.cql:/docker-entrypoint-initdb.d/cassandra-keyspace.cql
    ports: 
      - 9042:9042
    environment: 
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    networks: 
      - backend

  graphql_server:
    container_name: gqlserver
    depends_on:
      - db_postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../graphql-server:/usr/src/app
      - ./storage_config.json:/usr/src/app/config/data_models_storage_config.json
      - ./seedUserDb.sql:/usr/src/seedUserDb.sql
      - ./migrateDbAndStartServer.sh:/usr/src/app/migrateDbAndStartServer.sh
      - .env:/usr/src/app/.env
    ports:
      - 3000:3000
    environment:
      JQ_PATH: /usr/bin/jq
      LIMIT_RECORDS: 100
      PGPASSWORD: zendro
      PORT: 3000
      REQUIRE_SIGN_IN: "false"
    networks:
      - backend
      - frontend
    command:
      - /bin/sh
      - -c
      - |
        ./migrateDbAndStartServer.sh

  spa:
    stdin_open: true
    container_name: spa
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../single-page-app:/usr/src/app
    ports:
     - 8081:3000
    environment:
      JQ_PATH: /usr/bin/jq
      REACT_APP_ZENDRO_MAX_RECORD_LIMIT: 100
      REACT_APP_ZENDRO_GRAPHQL_SERVER_URL: http://localhost:3000/graphql
      REACT_APP_ZENDRO_LOGIN_URL: http://localhost:3000/login
      REACT_APP_ZENDRO_EXPORT_URL: http://localhost:3000/export
      REACT_APP_ZENDRO_MAX_UPLOAD_SIZE: 500
    networks:
      - frontend
    command:
      - /bin/sh
      - -c
      - |
        npm start


  graphiql:
    container_name: graphiql-auth
    restart: unless-stopped
    stdin_open: true
    depends_on:
      - db_postgres
      - graphql_server
    build:
      context: .
      dockerfile: Dockerfile.graphiql
    environment:
      REACT_APP_SERVER_URL: "http://localhost:3000/graphql"
      REACT_APP_LOGIN_URL: "http://localhost:3000/login"
      PORT: "7000"
    networks:
      - backend
    ports:
      - "7000:7000"
    volumes:
      - ../graphiql-auth:/usr/src/app
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm start

networks:
  backend:
  frontend: